### ISSUE TITLE
Installation issues through fiji plugin manager across multiple devices

### ISSUE THREAD

**Issue by david115599** [anotherche/photobend#2]
I have been having trouble installing Photobend across multiple devices using the fiji plugin manager. It is claiming that the source URL is invalid / missing required files like db.xml.gz

![image](https://github.com/anotherche/photobend/assets/6025258/d3724d06-a134-44f8-862c-5fd14dd25abd)
![image](https://github.com/anotherche/photobend/assets/6025258/34ec6b63-9d78-4a98-adb4-9a933c15f68c)
![image](https://github.com/anotherche/photobend/assets/6025258/4c84916f-0cae-4dd3-817f-d807ec372247)

**Comment by anotherche** [comment]
Hi, @david115599! Unfortunately, some wiki-pages retain outdated information about the address of the update site. The current address of the plugin: https://sites.imagej.net/PhotoBend/
You probably found this old address at https://imagej.net/plugins/photobend. Thanks for reminding me of it.

**Comment by david115599** [comment]
Thanks for the help. The new address worked
